server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/food_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Rahul7488@##

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
